openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of students app
tags:
  - name: Product
    description: Operations about product.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /products:
    get:
      $ref: ../swagger/path/products/get.yaml
    post:
      $ref: ../swagger/path/products/post.yaml
  /products/{id}:
    get:
      $ref: ../swagger/path/products/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
