type: object
required:
  - _id
  - name
  - price
properties:
  _id:
    description: "Product's id"
    type: string
    example: 65e4decdd286b30065d54af9
  name:
    description: "Product's name"
    type: string
    example: 'John Doe'
  price:
    description: "Product's price"
    type: number
    example: 12
  category:
    description: "Product's category"
    type: string
    enum: ['books', 'electronics', 'clothing', 'other']
  description:
    description: "Product's description"
    type: string
    example: Some description
